# Generated by Django 5.2.8 on 2025-11-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torneoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo",
            name="puntos",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partido",
            name="fase",
            field=models.CharField(
                choices=[
                    ("GRUPOS", "Fase de Grupos"),
                    ("SEMIFINAL", "Semifinal"),
                    ("FINAL", "Final"),
                ],
                default="GRUPOS",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="partido",
            name="resultado_equipo1",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="partido",
            name="resultado_equipo2",
            field=models.IntegerField(default=0),
        ),
    ]
